language: php

php:
    - 7.3
    - 7.4

install:
    - composer install

before_script:
    - pecl install uopz-6.1.0

script:
    - mkdir -p ./var/build
    - ./vendor/bin/phpunit --coverage-clover ./var/build/coverage.xml
    - ./vendor/bin/phpcs -s

after_script:
    -   |
        echo "Coveralls Upload"
        if [ -f "./var/build/coverage.xml" ]; then
            travis_retry ./vendor/bin/php-coveralls -x ./var/build/coverage.xml -o ./var/build/coveralls-upload.json -v;
            echo "Coverage submitted to Coveralls"
        else
            echo "./var/build/coverage.xml not found, coverage not submitted to Coveralls"
        fi
