language: php

php:
    - 7.3
    - 7.4

install:
    - composer install

script:
    - mkdir -p ./var/build
    - phpunit --coverage-clover ./var/build/coverage.xml

after_success:
    - travis_retry ./vendor/bin/php-coveralls -x ./var/build/coverage.xml -o ./var/build/coveralls-upload.json -v
